# -*- coding: utf-8 -*-
"""Loan approval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBrNBH5XtLqWaKLkgBuCtaAs6JhxJ4fU
"""

pip install pandas

import pandas as pd
df=pd.read_csv('loan_data.csv')
df.head()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df=pd.read_csv('loan_data.csv')
df.head()

df.info()
df.isnull().sum()

for col in df.select_dtypes(include='object').columns:
    df[col].fillna(df[col].mode()[0], inplace=True)
for col in df.select_dtypes(include=np.number).columns:
    df[col].fillna(df[col].median(), inplace=True)
df.isnull().sum()

le=LabelEncoder()
df['loan_status']=le.fit_transform(df['loan_status'])
categorical_cols=df.select_dtypes(include='object').columns
df=pd.get_dummies(df, columns=categorical_cols, drop_first=True)
df.head()

x=df.drop('loan_status', axis=1)
y=df['loan_status']
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=42)

scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

model=LogisticRegression()
model.fit(x_train, y_train)
y_pred=model.predict(x_test)

print(f"Accurary: {accuracy_score(y_test, y_pred):.2f}")
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()
print(classification_report(y_test, y_pred))